# Install script for directory: ${CMAKE_SOURCE_DIR}

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/../dcmtk-3.5.4-win32-i386")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/doc" TYPE FILE FILES
    "${CMAKE_SOURCE_DIR}/COPYRIGHT"
    "${CMAKE_SOURCE_DIR}/FAQ"
    "${CMAKE_SOURCE_DIR}/HISTORY"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("${CMAKE_SOURCE_DIR}/config/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/ofstd/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmdata/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmtls/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmnet/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmqrdb/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmimgle/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmimage/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmjpeg/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmsign/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmsr/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmpstat/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/dcmwlm/cmake_install.cmake")
  INCLUDE("${CMAKE_SOURCE_DIR}/doxygen/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "${CMAKE_SOURCE_DIR}/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "${CMAKE_SOURCE_DIR}/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
